// Daily Inspiration Quotes Collection
const DAILY_QUOTES = [
    { text: "You have power over your mind — not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
    { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius" },
    { text: "If it is not right, do not do it; if it is not true, do not say it.", author: "Marcus Aurelius" },
    { text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius" },
    { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius" },
    { text: "The best revenge is to be unlike him who performed the injury.", author: "Marcus Aurelius" },
    { text: "When you arise in the morning, think of what a privilege it is to be alive.", author: "Marcus Aurelius" },
    { text: "Very little is needed to make a happy life; it is all within yourself.", author: "Marcus Aurelius" },
    { text: "Accept the things to which fate binds you, and love the people with whom fate brings you together.", author: "Marcus Aurelius" },
    { text: "It never ceases to amaze me: we all love ourselves more than other people, but care more about their opinions than our own.", author: "Marcus Aurelius" },
    { text: "The soul becomes dyed with the color of its thoughts.", author: "Marcus Aurelius" },
    { text: "You have power over your mind, not outside events.", author: "Marcus Aurelius" },
    { text: "Do every act of your life as though it were the very last act of your life.", author: "Marcus Aurelius" },
    { text: "The things you think about determine the quality of your mind.", author: "Marcus Aurelius" },
    { text: "Confine yourself to the present.", author: "Marcus Aurelius" },
    { text: "The universe is change: life is opinion.", author: "Marcus Aurelius" },
    { text: "He who lives in harmony with himself lives in harmony with the universe.", author: "Marcus Aurelius" },
    { text: "Our life is what our thoughts make it.", author: "Marcus Aurelius" },
    { text: "Nothing happens to any man which he is not formed by nature to bear.", author: "Marcus Aurelius" },
    { text: "Look well into thyself; there is a source of strength which will always spring up if thou wilt always look.", author: "Marcus Aurelius" },
    { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
    { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca" },
    { text: "He who is brave is free.", author: "Seneca" },
    { text: "Difficulties strengthen the mind, as labor does the body.", author: "Seneca" },
    { text: "It is not that we have a short time to live, but that we waste a lot of it.", author: "Seneca" },
    { text: "We are more often frightened than hurt; and we suffer more in imagination than in reality.", author: "Seneca" },
    { text: "No man was ever wise by chance.", author: "Seneca" },
    { text: "If one does not know to which port one is sailing, no wind is favorable.", author: "Seneca" },
    { text: "True happiness is to enjoy the present, without anxious dependence upon the future.", author: "Seneca" },
    { text: "A gift consists not in what is done or given, but in the intention of the giver.", author: "Seneca" },
    { text: "While we wait for life, life passes.", author: "Seneca" },
    { text: "Begin at once to live, and count each separate day as a separate life.", author: "Seneca" },
    { text: "It is a rough road that leads to the heights of greatness.", author: "Seneca" },
    { text: "The greatest remedy for anger is delay.", author: "Seneca" },
    { text: "He who spares the wicked injures the good.", author: "Seneca" },
    { text: "We should give as we would receive, cheerfully, quickly, and without hesitation.", author: "Seneca" },
    { text: "Associate with people who are likely to improve you.", author: "Seneca" },
    { text: "Sometimes even to live is an act of courage.", author: "Seneca" },
    { text: "A man who suffers before it is necessary, suffers more than is necessary.", author: "Seneca" },
    { text: "Luck never made a man wise.", author: "Seneca" },
    { text: "No great thing is created suddenly.", author: "Epictetus" },
    { text: "It's not what happens to you, but how you react to it that matters.", author: "Epictetus" },
    { text: "First say to yourself what you would be; and then do what you have to do.", author: "Epictetus" },
    { text: "We have two ears and one mouth so that we can listen twice as much as we speak.", author: "Epictetus" },
    { text: "Freedom is the only worthy goal in life.", author: "Epictetus" },
    { text: "Don't explain your philosophy. Embody it.", author: "Epictetus" },
    { text: "The key is to keep company only with people who uplift you.", author: "Epictetus" },
    { text: "Circumstances don't make the man, they only reveal him to himself.", author: "Epictetus" },
    { text: "If you want to improve, be content to be thought foolish and stupid.", author: "Epictetus" },
    { text: "We cannot choose our external circumstances, but we can always choose how we respond to them.", author: "Epictetus" },
    { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
    { text: "Simplicity is the soul of efficiency.", author: "Austin Freeman" },
    { text: "Make each day your masterpiece.", author: "John Wooden" },
    { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
    { text: "Focus on being productive instead of busy.", author: "Tim Ferriss" },
    { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
    { text: "Small daily improvements over time lead to stunning results.", author: "Robin Sharma" },
    { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
    { text: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
    { text: "Well begun is half done.", author: "Aristotle" },
    { text: "Stay hungry, stay foolish.", author: "Stewart Brand" },
    { text: "Either you run the day or the day runs you.", author: "Jim Rohn" },
    { text: "What we achieve inwardly will change outer reality.", author: "Plutarch" },
    { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
    { text: "Dream big and dare to fail.", author: "Norman Vaughan" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
    { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
    { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
    { text: "Happiness depends upon ourselves.", author: "Aristotle" },
    { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "Begin anywhere.", author: "John Cage" },
    { text: "Creativity is intelligence having fun.", author: "Albert Einstein" },
    { text: "Clutter is nothing more than postponed decisions.", author: "Barbara Hemphill" },
    { text: "To live a creative life, we must lose our fear of being wrong.", author: "Joseph Chilton Pearce" },
    { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
    { text: "Done is better than perfect.", author: "Sheryl Sandberg" },
    { text: "Light tomorrow with today.", author: "Elizabeth Barrett Browning" },
    { text: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
    { text: "If you want to fly, you have to give up the things that weigh you down.", author: "Toni Morrison" },
    { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
    { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
    { text: "An unexamined life is not worth living.", author: "Socrates" },
    { text: "Adopt the pace of nature: her secret is patience.", author: "Ralph Waldo Emerson" },
    { text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
    { text: "There is no substitute for hard work.", author: "Thomas Edison" },
    { text: "Turn your face towards the sun and the shadows fall behind you.", author: "Maori Proverb" },
    { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
    { text: "A year from now you may wish you had started today.", author: "Karen Lamb" },
    { text: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
    { text: "The mind is everything. What you think you become.", author: "Buddha" },
    { text: "Mastering others is strength. Mastering yourself is true power.", author: "Lao Tzu" },
    { text: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt" },
    { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
    { text: "Silence is a source of great strength.", author: "Lao Tzu" }
];

// Attach to window for global access across extension scripts
if (typeof window !== 'undefined') {
    window.DAILY_QUOTES = DAILY_QUOTES;
}
